FROM ubuntu

RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y default-jdk default-jre git vim emacs

# to build
# docker build -t ex04_java .

# to run
# docker run --rm -ti ex04_java